name: chat
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  tiktoklikescroller: ^0.1.8
  get: ^4.3.8
  package_info: ^2.0.2
  uni_links: ^0.5.1
  crypto: ^3.0.1
  hexcolor: ^2.0.5
  logger: ^1.1.0
  flutter_easyloading: ^3.0.3
  flutter_secure_storage: ^5.0.0-beta.5
  flutter_dotenv: ^5.0.2
  json_annotation: ^4.3.0
  shared_preferences: ^2.0.8
  settings_ui: ^1.0.0
  responsive_framework: ^0.1.5
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
dev_dependencies:
  flutter_lints: ^1.0.0
  lints: ^1.0.1
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.0
  json_serializable: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
