name: chat
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flare_flutter: ^3.0.2
  tiktoklikescroller: ^0.1.8
  pin_code_fields: ^7.3.0
  intl_phone_number_input:
    git:
      url: git@github.com:susuwoniu/intl_phone_number_input.git
      ref: b694b94cc3a6484fe4699d7d41a133a6f8fd80ad
  get: ^4.3.8
  package_info: ^2.0.2
  crypto: ^3.0.1
  hexcolor: ^2.0.5
  logger: ^1.1.0
  flutter_easyloading: ^3.0.3
  flutter_secure_storage: ^5.0.0-beta.5
  flutter_dotenv: ^5.0.2
  json_annotation: ^4.3.0
  shared_preferences: ^2.0.8
  settings_ui: ^1.0.0
  responsive_framework: ^0.1.5
  scrollable_positioned_list: ^0.2.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
dev_dependencies:
  flutter_lints: ^1.0.0
  lints: ^1.0.1
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.0
  json_serializable: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/
