name: chat
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: ^4.3.8
  package_info: ^2.0.2
  crypto: ^3.0.1
  flutter_easyloading: ^3.0.3
  shared_preferences: ^2.0.8
  flutter: 
    sdk: flutter
  flutter_localizations:
    sdk: flutter
dev_dependencies: 
  flutter_lints: ^1.0.0
  lints: ^1.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
