name: chat
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  # csc_picker: ^0.2.6
  infinite_scroll_pagination: ^3.1.0
  flutter_share_me:
    git:
      url: git@github.com:OpenFlutter/flutter_share_me.git
  animated_toggle_switch: ^0.2.1
  image_cropper: ^1.4.1
  location: ^4.3.0
  carousel_slider: ^4.0.0
  dotted_border: ^2.0.0+1
  image_picker: ^0.8.4+4
  file_picker: ^4.2.7
  circular_profile_avatar: ^2.0.5
  mime_type: ^1.0.0
  open_file: ^3.2.1
  cupertino_icons: ^1.0.2
  flare_flutter: ^3.0.2
  tab_indicator_styler: ^2.0.0
  tiktoklikescroller:
    path: ../tiktok-flutter-plugin
  tcard: ^1.3.5
  uni_links: ^0.5.1
  # text_editor: ^0.7.0
  text_editor:
    path: ../instagram-text-editor
  pin_code_fields: ^7.3.0
  intl_phone_number_input:
    git:
      url: git@github.com:susuwoniu/intl_phone_number_input.git
      ref: b694b94cc3a6484fe4699d7d41a133a6f8fd80ad
  # get: ^4.6.1
  get:
    git:
      url: git@github.com:theowenyoung/getx.git
  # get:
  #   path: ../../inbox/getx
  #   version: ^4.6.1
  flutter_phoenix: "^1.0.0"
  flutter_markdown: ^0.6.9
  # get_storage: ^2.0.3
  get_storage:
    git:
      url: git@github.com:theowenyoung/get_storage.git
  timer_count_down: ^2.2.0
  path_provider: ^2.0.7
  package_info: ^2.0.2
  crypto: ^3.0.1
  hexcolor: ^2.0.5
  logger: ^1.1.0
  flutter_easyloading: ^3.0.3
  flutter_secure_storage: ^5.0.0-beta.5
  flutter_dotenv: ^5.0.2
  cached_network_image: ^3.2.0
  date_format: ^2.0.4
  json_annotation: ^4.3.0
  shared_preferences: ^2.0.8
  # settings_ui: ^1.0.0
  # 2.8 fix, wait https://github.com/yako-dev/flutter-settings-ui/pull/101 merged
  settings_ui:
    git:
      url: git@github.com:beerstorm-net/flutter-settings-ui.git
  responsive_framework: ^0.1.5
  scrollable_positioned_list: ^0.2.2
  permission_handler: ^8.3.0
  platform_device_id: ^1.0.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  rxdart: ^0.27.2
  clipboard: ^0.1.3
  flutter_chat_ui: ^1.5.3
  # flutter_chat_ui:
  #   path: ../flutter_chat_ui
  sprintf: ^6.0.0
  # xmpp_stone:
  #   git:
  #     url: git@github.com:theowenyoung/xmpp_client.git
  #     ref: main
  xmpp_stone:
    path: ../xmpp_client
dev_dependencies:
  flutter_lints: ^1.0.0
  lints: ^1.0.1
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.0
  json_serializable: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/
