const String DEV_API_HOST = "https://chat.scuinfo.com";
const String PROD_API_HOST = "https://chat.scuinfo.com";
const String DEV_IM_DOMAIN = "xmpp.scuinfo.com";
const String PROD_IM_DOMAIN = "xmpp.scuinfo.com";
const String MAIN_HOST = "https://www.scuinfo.com";
const String API_PATH_PREFIX = "/api/v1";
const String DEV_IOS_CLIENT_ID = "377827351943197187";
const String DEV_ANDROID_CLIENT_ID = "377844742802649603";
// TODO change when online
const String PROD_IOS_CLIENT_ID = "377827351943197187";
const String PROD_ANDROID_CLIENT_ID = "377844742802649603";
const String DEV_IOS_CLIENT_SECRET_KEY = "DEV_IOS_CLIENT_SECRET";
const String DEV_ANDROID_CLIENT_SECRET_KEY = "DEV_ANDROID_CLIENT_SECRET";
const String PROD_IOS_CLIENT_SECRET_KEY = "PROD_IOS_CLIENT_SECRET";
const String PROD_ANDROID_CLIENT_SECRET_KEY = "PROD_ANDROID_CLIENT_SECRET";
const String LOCAL_API_HOST_KEY = "LOCAL_API_HOST";
