const Map<String, String> en_US = {
  'EditInfoView': 'Edit Info',
  'FeedbackView': 'Feedback',
  'Screenshot_for_troubleshooting(Optional)':
      'Screenshot for troubleshooting(Optional)',
  'Please_describe_your_issue_using_at_least_10_characters_so_that_we_can_help_troubleshoot_your_issue_more_quickly':
      'Please describe your issue using at least 10 characters so that we can help troubleshoot your issue more quickly',
  'Please_describe_your_issue_using_at_least_10_characters':
      'Please using at least 10 characters',
  'mobile_email_contact': 'Mobile/Email Contact',
  'Thank_you_for_feedback': 'Thank you for feedback~',
  'Optional': 'Optional',
  'Avatar': 'Avatar',
  'MeView': 'My Profile',
  'More': 'More',
  'ReportView': 'Report',
  'Bio': 'About Me',
  'Nickname': 'Name',
  'please_enter_at_least_two_characters.':
      'Please enter at least two characters.',
  'SinglePost': 'Post',
  's_post': "'s post",
  'ProfileViewersView': 'Who Saw Me',
  'PostView': 'Create A Post',
  'SettingView': 'Settings',
  'Room': 'Room',
  'Loading': 'Loading',
  'Loading...': 'Loading...',
  'Connecting...': "Connecting...",
  'Network_error': 'Network error',
  'Chats': 'Chats',
  'Chat': 'Chat',
  'Home': "Home",
  'Nearby': "Nearby",
  'no_more_now': 'No more now...',
  'no_more': 'No more...',
  'Login': 'Login',
  'Account_Security': "Account",
  'Phone': "Phone",
  'Successfully_filtered': 'Filtered',
  'Successfully_polished': 'Polished~',
  'Successfully_deleted': 'Deleted.',
  'Blocked': 'Blocked.',
  'Unblocked': 'Unblocked.',
  'Liked!': 'Liked!',
  'Successfully_unliked': 'Unliked.',
  'Thank_you_for_reporting!': 'Thank you for reporting!',
  'Please_choose_a_report_type': 'Please choose a report type.',
  'About': "About",
  'Privacy': 'Privacy',
  'Liked': 'Liked',
  'Like': 'Like',
  'Who_Likes_Me': 'Who Likes Me',
  'Blocked_List': 'Blocked List',
  'Unblock': 'Unblock',
  'Block': 'Block',
  'Clear_Cache': "Clear Cache",
  'Help&Feedback': "Help & Feedback",
  'Log_out': "Log out",
  'title': 'Title',
  "Choose_a_Topic": 'Choose a Topic',
  'Verification': 'Verification',
  'login': 'user @name，mail @email',
  "General": "General",
  "Language": "Language",
  "English": "English",
  "Simplified-Chinese": "Simplified-Chinese",
  "theme": "Theme",
  "Night-mode": "Night-mode",
  "message": "Message",
  "Message": "Message...",
  "login_title": "Login",
  "unknow_error_title": "Unknow error title",
  "request_cancel": "Request Canceled",
  "request_timeout": "Request Timeout",
  "receive_timeout": "Receive Timeout",
  "unknow_error": "Unknow error",
  "Reply": "Reply",
  "bad_request_error": "Bad request error",
  "unauthorized_error": "Please Login First~",
  "forbidden_error": "You don't have permission to view this page.",
  "not_found_error": "Not found error",
  "method_not_allowed_error": "Method not allowed error",
  "server_internal_error": "Server internal error",
  "too_many_requests_error": "Too many requests error",
  "too_many_requests_detail": "Too many requests detail",
  "client_network_error": "Client network error",
  "response_data_invalid": "Response data invalid",
  "please_enter_correct_phone_number": "Please enter a valid phone number.",
  "please_fill_up_all_the_cells_properly": "Please enter verification code.",
  "we_have_sent_the_code_to_your_phone":
      "We have sent a verification code to your phone:",
  "didn_t_receive_the_code": "I haven't received the verification code.",
  " secends": " secends",
  "Send": "Send",
  "succeeded": "Succeeded!",
  'A_verification_code_has_been_sent_to_your_phone':
      'A verification code has been sent to your phone.',
  'Logged_out': 'Logged out.',
  "Resend": "Resend Code",
  "Submit": "Submit",
  "phone_number": "phone",
  "what_s_your_phone_number": "What's your phone number?",
  "next": "next",
  'Next': 'Next',
  "error_occured": "Error occured",
  "renew_token_failed": "Renew token failed",
  "Name": "Name",
  "gender": "gender",
  "location": "location",
  "tags": "tags",
  "birth": "birth",
  'Birth': 'Birth',
  "Save": "Save",
  "Please_choose_your_gender_and_age": "Please choose your gender and age:",
  "I_am": "I am:",
  "I_was_born_in": "I was born in:",
  "female": "female",
  "male": "male",
  "other": "other",
  "Find_Friends": "Find Friends",
  'Last_visit: ': 'Last Visit: ',
  ' Visitors': ' Visitors',
  ' Visitor': ' Visitor',
  'Chat_now': 'Chat Now',
  "visited_you": "visited you",
  "times": "times",
  " Posts": " Posts",
  " Post": " Post",
  ' Hearts': ' Hearts',
  ' Heart': ' Heart',
  "Public": "Public",
  "Private": "Private",
  'Visible_to_yourself': 'Visible to Yourself',
  'Visible_to_public': 'Visible to Public',
  "Filter": "Filter",
  "Age": "Age",
  'years_old': 'years old',
  "Gender": "Gender",
  "Location": "Location",
  "Distance": "Distance",
  'Unbound_phone': 'Unbound phone',
  "OK": "OK",
  "Reset": "Reset",
  "All": "All",
  "Female": "Female",
  "Male": "Male",
  "Report": "Report",
  "share": "Share App",
  'pravicy': 'Pravicy',
  'km': ' KM',
  'something_went_wrong': 'Something went wrong',
  'refresh': 'Refresh',
  'receive_push_notification': 'Receive Push Notification',
  'rate_us_on_app_store': 'Rate us on App Store',
  'user_agreement': 'User Agreement',
  "Join_topic": "Join Topic",
  "Choose_report_type": "Choose Report Type",
  'You_have_been_blocked': 'You have been blocked.',
  'there_is_nothing_here': 'There is nothing here...',
  "Enter_report_description(Optional)": "Enter report description(Optional)",
  'Screenshot_of_Evidence(Optional)': 'Screenshot of Evidence(Optional)',
  'Fraud': 'Fraud',
  'Harassing': 'Harassing',
  'Crime_and_illegal_activities': 'Crime and illegal activities',
  'Other': 'Other',
  'Visibility': 'Visibility',
  'Polish': 'Polish',
  'Delete': 'Delete',
  'Cancel': 'Cancel',
  'Ban': 'Ban',
  'Create_Post': 'Create Post',
  'Create': 'Create',
  'unlocks_at': 'Unlocks at:',
  'To_Purchase': 'To Purchase',
  'special_icon': 'Special Icon',
  'display-specific_logo': 'Display member-specific logo',
  'view_likes': 'View Likes',
  'see_who_liked_me': 'See who liked me',
  'choose_persons_you_are_interested_in':
      'Choose persons you are interested in',
  'your_post_will_be_pushed_to_the_latest':
      'Your post will be pushed to the latest',
  'unlimited_posts': 'Unlimited Posts',
  'get_unlimited_posts': 'Get unlimited posts',
  'unlimited_favorites': 'Unlimited favorites',
  'get_unlimited_favorites': 'Get unlimited favorites',
  'more_features': 'More Features',
  'we_will_develop_more_membership_features':
      'We will develop more membership features~',
  '1_week': '1 week',
  '1_month': '1 month',
  '3_months': '3 months',
  '6_months': '6 months',
  '1_year': '1 year',
  'Unknown_place': 'Unknown Place',
  'Nothing...': 'Nothing...',
  'Unknown': 'Unknown',
  'No_one_has_been_here': 'No one has been here.',
  "Please_take_care": "Please take care.",
  "Submit_confirm": "Submit confirm",
  "Tips": "Tips",
  "Confirm": "Confirm",
  'Skip': 'Skip',
  "Give_yourself_a_nice_name": "Give yourself a nice name.",
  "Give_yourself_a_nice_bio": "Give yourself a nice bio.",
  'CompleteAge': 'Choose Age',
  "ChangeGender": "Choose Gender",
  "CompleteGender": "Choose Gender",
  "CompleteName": 'Edit Name',
  'CompleteBio': 'Edit Bio',
  'CompleteAvatar': 'Edit Avatar',
  "I_agree_rules": "I agree rules.",
  'Please_choose_a_photo_that_best_represents_you':
      'Please choose a photo that best represents you.',
  'Photo_can_be_edited_later': 'Photo can be edited later.',
  "Finish": "Finish",
  'viewed_your_post': 'viewed your post',
  "no_one_has_seen_this_post...": "No one has seen this post...",
  'This_user_left_nothing...': 'This user left nothing...',
  'Confirm_to_delete?': 'Confirm to delete?',
  'Pin': 'Pin',
  "It_can't_be_polished_any_more.": "It can't be polished any more.",
  "It's_not_time_to_post_yet": "It's not time to post yet.",
  'Marked.': 'Favorited.',
  'Marked': 'Favorited',
  'Mark': "Favorite",
  ' Mark': 'Favorite',
  ' Marks': ' Favorites',
  'StarView': 'My Favorites',
  'In_chronological_order': 'In Chronological Order',
  'By_hot_degree': 'By Hot Degree',
  'ExploreView': 'Explore Topics'
};
