const Map<String, String> zh_Hans = {
  'title': '这是标题',
  'login': '登录用户 @name，邮箱账号 @email',
  "general": "通用",
  "language": "语言",
  "english": "英语",
  "simplified-chinese": "中文简体",
  "theme": "主题",
  "night-mode": "夜间模式",
  "message": "消息",
  "login_title": "登录",
  "unknow_error_title": "未知错误",
  "request_cancel": "请求取消",
  "request_timeout": "请求超时",
  "receive_timeout": "响应超时",
  "unknow_error": "未知错误",
  "bad_request_error": "请求格式有误",
  "unauthorized_error": "请先登录",
  "forbidden_error": "没有权限访问该内容",
  "not_found_error": "没有找到该资源",
  "method_not_allowed_error": "没有找到该资源",
  "server_internal_error": "服务器开小差了",
  "too_many_requests_error": "请求太快了",
  "too_many_requests_detail": "喝杯水再试"
};
